version: "3.4"
services:
    postgresql:
        image: postgres:12.5
        ports:
            - "${POSTGRES_PORT}:5432"
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - stalker-db:/var/lib/postgresql/data:delegated

        networks:
            - lol-charts-network

    adminer:
        image: adminer
        restart: always
        ports:
            - "${ADMINER_PORT}:8080"
        networks:
            - lol-charts-network

volumes:
    stalker-db:

networks:
    lol-charts-network:
        driver: bridge
