version: "3.4"
services:
    server:
        build: .
        ports:
            - "${BACKEND_PORT}:8080"
        restart: always
        depends_on:
            - postgresql
        networks:
            - lol-charts-network

    postgresql:
        image: postgres:12.5
        ports:
            - "5432"
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - stalker-db:/var/lib/postgresql/data:delegated

        networks:
            - lol-charts-network

    adminer:
        image: adminer
        restart: always
        depends_on:
            - postgresql
        ports:
            - "8080"
        networks:
            - lol-charts-network

volumes:
    stalker-db:

networks:
    lol-charts-network:
        driver: bridge
