version: "3.4"
services:
    server:
        image: "ghcr.io/ledouxm/lol-elo-charts:main"
        ports:
            - "8080"
        environment:
            HTTP_PORT: 8080
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_HOST: ${POSTGRES_HOST}

            VIRTUAL_HOST: ${VIRTUAL_HOST}
            LETSENCRYPT_HOST: ${VIRTUAL_HOST}
        depends_on:
            - postgresql
        networks:
            - nginx-network
            - lol-charts-network
        profiles:
            - production

    postgresql:
        image: postgres:12.5
        ports:
            - "${POSTGRES_PORT}:5432"
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_HOST_AUTH_METHOD: trust
            POSTGRES_MULTIPLE_DATABASES: test
        volumes:
            # Persist data between up/down
            - postgresql:/var/lib/postgresql/data:delegated

        networks:
            - lol-charts-network

    adminer:
        image: adminer
        restart: always
        ports:
            - 8081:8080
        profiles:
            - development
        networks:
            - lol-charts-network

volumes:
    postgresql:

networks:
    lol-charts-network:
        driver: bridge
    nginx-network:
        external: true
        name: nginx-network
