version: "3.4"
services:
    server:
        image: lol-elo-charts
        build: .
        ports:
            - "${BACKEND_PORT}:8080"
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_USER: ${POSTGRES_USER}
            RG_API_KEY: ${RG_API_KEY}
            BOT_TOKEN: ${BOT_TOKEN}
            CRON_BETS_DELAY_MIN: ${CRON_BETS_DELAY_MIN}
            ENABLE_BETS: ${ENABLE_BETS}
            FORCE_RECAPS: ${FORCE_RECAPS}
            HTTP_PORT: ${HTTP_PORT}
            DISCORD_NOTIFICATION_INTERVAL_SEC: ${DISCORD_NOTIFICATION_INTERVAL_SEC}
            PLAYER_REQUEST_INTERVAL_SEC: ${PLAYER_REQUEST_INTERVAL_SEC}
            VALORANT_DISCORD_NOTIFICATION_INTERVAL_SEC: ${VALORANT_DISCORD_NOTIFICATION_INTERVAL_SEC}
            VALORANT_PLAYER_REQUEST_INTERVAL_SEC: ${VALORANT_PLAYER_REQUEST_INTERVAL_SEC}
            DEBUG: ${DEBUG}
        restart: always
        depends_on:
            - postgresql
        networks:
            - lol-charts-network

    postgresql:
        image: postgres:12.5
        ports:
            - "${POSTGRES_PORT}:5432"
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - stalker-db:/var/lib/postgresql/data:delegated

        networks:
            - lol-charts-network

    adminer:
        image: adminer
        restart: always
        ports:
            - "${ADMINER_PORT}:8080"
        networks:
            - lol-charts-network

volumes:
    stalker-db:

networks:
    lol-charts-network:
        driver: bridge
