version: "3.4"
services:
    server:
        image: "ghcr.io/ledouxm/lol-elo-charts:${BRANCH}"
        ports:
            - "8080"
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_USER: ${POSTGRES_USER}
            RG_API_KEY: ${RG_API_KEY}
            VIRTUAL_HOST: ${VIRTUAL_HOST}
            LETSENCRYPT_HOST: ${VIRTUAL_HOST}
            BOT_TOKEN: ${BOT_TOKEN}
            CRON_RANK_DELAY_MIN: ${CRON_RANK_DELAY_MIN}
            CRON_BETS_DELAY_MIN: ${CRON_BETS_DELAY_MIN}
            ENABLE_BETS: ${ENABLE_BETS}
            FORCE_RECAPS: ${FORCE_RECAPS}
        depends_on:
            - postgresql
        networks:
            - nginx-network
            - lol-charts-network
        profiles:
            - production

    postgresql:
        image: postgres:12.5
        ports:
            - "${POSTGRES_PORT}:5432"
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_HOST_AUTH_METHOD: trust
            POSTGRES_MULTIPLE_DATABASES: test
        volumes:
            - postgresql:/var/lib/postgresql/data:delegated

        networks:
            - lol-charts-network

    adminer:
        image: adminer
        environment:
            VIRTUAL_HOST: ${ADMINER_VIRTUAL_HOST}
            LETSENCRYPT_HOST: ${ADMINER_VIRTUAL_HOST}
        restart: always
        ports:
            - "8080"
        networks:
            - nginx-network
            - lol-charts-network

volumes:
    postgresql:

networks:
    lol-charts-network:
        driver: bridge
    nginx-network:
        external: true
        name: nginx-network
