version: "3.4"
services:
    postgresql:
        image: postgres:12.5
        ports:
            - "${POSTGRES_PORT}:5432"
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - stalker-db:/var/lib/postgresql/data:delegated

        networks:
            - lol-charts-network

    explorer:
        image: ghcr.io/ledouxm/kysely-explorer:0.0.2
        restart: always
        environment:
            FIRST_CONNECTION_TOKEN: ${FIRST_CONNECTION_TOKEN}
            AUTH_SECRET: ${AUTH_SECRET}
        ports:
            - "${EXPLORER_PORT}:3005"
        networks:
            - lol-charts-network

volumes:
    stalker-db:

networks:
    lol-charts-network:
        driver: bridge
