version: "3.4"
services:
    server:
        build: .
        restart: always
        depends_on:
            - postgresql
        networks:
            - lol-charts-network

    postgresql:
        image: postgres:12.5
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - stalker-db:/var/lib/postgresql/data:delegated

        networks:
            - lol-charts-network

    adminer:
        image: adminer
        restart: always
        depends_on:
            - postgresql
        networks:
            - lol-charts-network

volumes:
    stalker-db:

networks:
    lol-charts-network:
        driver: bridge
