version: "3.4"
services:
    # https://hub.docker.com/_/postgres
    server:
        image: "ghcr.io/ledouxm/monorepo-with-ci:main"
        ports:
            - "${HTTP_PORT}:8080"
        environment:
            HTTP_PORT: ${HTTP_PORT}
            POSTGRES_PORT: ${POSTGRES_PORT}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}

    postgresql:
        image: postgres:12.5
        ports:
            - "${POSTGRES_PORT}:5432"
        environment:
            POSTGRES_PORT: ${POSTGRES_PORT}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_HOST_AUTH_METHOD: trust
            POSTGRES_MULTIPLE_DATABASES: test
        volumes:
            # Persist data between up/down
            - postgresql:/var/lib/postgresql/data:delegated

            # When data volume is empty, start every scripts in folder in A-Z order
            - ./packages/server/docker/postgres/:/docker-entrypoint-initdb.d/

    adminer:
        image: adminer
        ports:
            - "8081:8080"
        environment:
            DATABASE_URL: postgres://postgres@postgresql:5432/platformer
        depends_on:
            - postgresql

volumes:
    postgresql:
