name: Publish Docker image and deploy prod

on:
    push:
        branches: [main]

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    push_to_registry:
        name: Push Docker image to Github Packages
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v2

            - name: Log in to Github Packages
              uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Docker meta
              id: docker_meta
              uses: crazy-max/ghaction-docker-meta@v1
              with:
                  images: l7r7/sample
                  tag-custom: latest
                  tag-semver: |
                      {{raw}}
            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.docker_meta.outputs.labels.org.opencontainers.image.revision }}

            - name: Build and push Docker image
              uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
              with:
                  context: .
                  push: true
                  tags: ${{ steps.docker_meta.outputs.tags }}
                  labels: ${{ steps.docker_meta.outputs.labels }}
            - name: deploy to portainer
              uses: fjogeleit/http-request-action@master
              with:
                  url: ${{ secrets.PORTAINER_WEBHOOK }}?IMAGE_NAME=${{ steps.docker_meta.outputs.labels.org.opencontainers.image.revision }}
